[phases.setup]
nixPkgs = ["libssl", "pkg-config", "openssl", "php", "php81Extensions.mongodb"]

[phases.build]
cmds = [
    "pecl install mongodb",
    "docker-php-ext-enable mongodb",
    "composer install",
    "npm install --production",
    "php artisan optimize",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache",
    "php artisan migrate --force"
]
